<?php

/**
 * @file
 * Allows users to authenticate themselves via Hawk authentication.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hawk_auth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hawk_auth':
      $output = '<p>' . t('Hawk Authentication provides an alternative to Basic Authentication and Cookie
                           for authenticating client, primarily intended for REST use. Users need to be
                           granted permission in order to be able to create authentication keys from their
                           profile. See <a href="http://github.com/hueniverse/hawk">Hawk</a> for more information
                           about the protocol') . '</p>';
      return $output;

    case 'hawk_auth.user_credential':
      $output = '<p>' . t('This page lists all the valid Hawk Credentials associated with your account.
                           When provuding ID for the client, use the ID listed against the key secret and not your
                           account ID.') . '</p>';
      return $output;

    case 'hawk_auth.user_credential_permissions':
      if (Drupal::currentUser()->id() == 1) {
        $output = '
          <div role="contentinfo" aria-label="' . t('Error message') . '" class="messages messages--error">
              <div role="alert">
                      <h2 class="visually-hidden">' . t('Error message') . '</h2>
                        ' . t('Users with ID #1 cannot revoke permissions due to the way Drupal internally handles permissions') . '
                    </div>
          </div>';
      }
      else {
        $output = '<p>' . t('All the selected permissions on this page are revoked for the current hawk
                             credential. When a client is connecting using this hawk credential, they
                             will not be allowed to perform any action that requires a permission
                             you revoke from here.') . '</p>';
      }
      return $output;
  }
}
