<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param string $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function hawk_auth_help($route_name, $route_match) {
  switch ($route_name) {
    case 'help.page.hawk_auth':
      $output = '<p>' . t('Hawk Authentication provides an alternative to Basic Authentication and Cookie ' .
                          'for authenticating client, primarily intended for REST use. Users need to be ' .
                          'granted permission in order to be able to create authentication keys from their ' .
                          'profile. See <a href="http://github.com/hueniverse/hawk">Hawk</a> for more information ' .
                          'about the protocol') . '</p>';
      return $output;
    case 'hawk_auth.user_credential':
      $output = '<p>' . t('This page lists all the valid Hawk Credentials associated with your account. ' .
                          'When provuding ID for the client, use the ID listed against the key secret and not your ' .
                          'account ID.') . '</p>';
      return $output;

  }
}