<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param string $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function hawk_help($route_name, $route_match) {
  switch ($route_name) {
    case 'hawk_auth.user_credential':
      $output = '<p>' . t('This page lists all the valid Hawk Credentials associated with your account. ' .
                          'When provuding ID for the client, use the ID listed against the key secret and not your ' .
                          'account ID.') . '</p>';
      return $output;

  }
}